export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCTS: "SELECTED_PROCUCTS",
    REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PROCUCTS",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART:"REMOVE_FROM_CART"
};